spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${OPENAI_MODEL:gpt-4o}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
          max-tokens: 2000
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      chat:
        # 启用OpenAI聊天模型
        enabled: true
        options:
          # 默认使用的模型
          model: ${DEEPSEEK_MODEL:deepseek-chat}
          # 默认温度参数 (1.0.0-M6版本使用Double类型)
          temperature: 0.7
          # 默认最大token数
#          org.springframework.ai.retry.NonTransientAiException: 400 - {"error":{"message":"Invalid max_tokens value, the valid range of max_tokens is [1, 8192]","type":"invalid_request_error","param":null,"code":"invalid_request_error"}}
          max-tokens: 8192
